<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class NetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('administrator')->table('net')->insert(
            [
                [
                    'connection_id'             => 4,
                    'name'                      =>'Red Manizales - UGR',
                    'description'               =>'Red de Estaciones Meteorológicas e Hidrometeorológicas Asociadas a la Prevención de Desastres en el Municipio de Manizales',
                    'administrator_name'        =>'Alexander Pachón',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 3,
                    'center_latitude_seconds'   => 35.9994,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 29,
                    'center_longitude_seconds'  => 23.9994,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 13,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 7,
                    'name'                      =>'SAT cuenca Q. El Guamo',
                    'description'               =>'Red de estaciones ubicadas en la cuenca de la quebrada El Guamo',
                    'administrator_name'        =>'Julián David Sánchez Hernández',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 4,
                    'center_latitude_seconds'   => 22.8,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 29,
                    'center_longitude_seconds'  => 42,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 13,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 7,
                    'name'                      =>'SAT cuenca Q. Olivares',
                    'description'               =>'Red de estaciones ubicadas en la cuenca de la quebrada Olivares',
                    'administrator_name'        =>'Julián David Sánchez Hernández',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 3,
                    'center_latitude_seconds'   => 50.7594,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 27,
                    'center_longitude_seconds'  => 34.5594,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 13,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 7,
                    'name'                      =>'SAT cuenca Q. Manizales',
                    'description'               =>'Red de estaciones ubicadas en la cuenca de la quebrada Manizales',
                    'administrator_name'        =>'Julián David Sánchez Hernández',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 3,
                    'center_latitude_seconds'   => 5.7594,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 27,
                    'center_longitude_seconds'  => 28.7994,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 13,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 7,
                    'name'                      =>'Red hidrometeorológica cuencas Manizales',
                    'description'               =>'Red de estaciones hidrometeorológicas ubicadas en diferentes cuencas del municipio de Manizales',
                    'administrator_name'        =>'Julián David Sánchez Hernández',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 3,
                    'center_latitude_seconds'   => 26.64,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 32,
                    'center_longitude_seconds'  => 28.76,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 12,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 2,
                    'name'                      =>'Red Caldas',
                    'description'               =>'Red de estaciones ubicada en el departamento de Caldas',
                    'administrator_name'        =>'Lorena Giraldo Gómez',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 12,
                    'center_latitude_seconds'   => 0,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 28,
                    'center_longitude_seconds'  => 48,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 9,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 5,
                    'name'                      =>'Red Nevados',
                    'description'               =>'Red de estaciones ubicada en el Parque natural Nacional los Nevados',
                    'administrator_name'        =>'Lorena Giraldo Gómez',
                    'center_latitude_degrees'   => 4,
                    'center_latitude_minutes'   => 53,
                    'center_latitude_seconds'   => 40.56,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 21,
                    'center_longitude_seconds'  => 58.32,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 11,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 6,
                    'name'                      =>'Red Udeger',
                    'description'               =>'Red de estaciones estaciones pertenecientes a la UDEGER',
                    'administrator_name'        =>'Anyela María Arias Guarin',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 1,
                    'center_latitude_seconds'   => 10.92,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 34,
                    'center_longitude_seconds'  => 28.56,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 12,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 3,
                    'name'                      =>'Red CHEC - Bocatomas',
                    'description'               =>'Red CHEC',
                    'administrator_name'        =>'',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 2,
                    'center_latitude_seconds'   => 52.44,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 36,
                    'center_longitude_seconds'  => 38.5194,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 11,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 1,
                    'name'                      =>'Red Calidad del Aire',
                    'description'               =>'Red de estaciones que miden la calidad del aire',
                    'administrator_name'        =>'Beatriz Helena Aristizabal',
                    'center_latitude_degrees'   => 5,
                    'center_latitude_minutes'   => 3,
                    'center_latitude_seconds'   => 52.44,
                    'center_latitude_direction' =>'N',
                    'center_longitude_degrees'  => 75,
                    'center_longitude_minutes'  => 31,
                    'center_longitude_seconds'  => 34.5594,
                    'center_longitude_direction'=>'W',
                    'rt_active'                 => true,
                    'map_zoom'                  => 12,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 1,
                    'name'                      =>'Red Cenicafé',
                    'description'               =>'Red de estaciones de datos históricos pertenecientes a Cenicafé',
                    'administrator_name'        => null,
                    'center_latitude_degrees'   => null,
                    'center_latitude_minutes'   => null,
                    'center_latitude_seconds'   => null,
                    'center_latitude_direction' => null,
                    'center_longitude_degrees'  => null,
                    'center_longitude_minutes'  => null,
                    'center_longitude_seconds'  => null,
                    'center_longitude_direction'=> null,
                    'rt_active'                 => false,
                    'map_zoom'                  => null,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 1,
                    'name'                      =>'Red Risaralda',
                    'description'               =>'Red de Risaralda',
                    'administrator_name'        => null,
                    'center_latitude_degrees'   => null,
                    'center_latitude_minutes'   => null,
                    'center_latitude_seconds'   => null,
                    'center_latitude_direction' => null,
                    'center_longitude_degrees'  => null,
                    'center_longitude_minutes'  => null,
                    'center_longitude_seconds'  => null,
                    'center_longitude_direction'=> null,
                    'rt_active'                 => false,
                    'map_zoom'                  => null,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ],
                [
                    'connection_id'             => 1,
                    'name'                      =>'Red Aguas Freáticas',
                    'description'               =>'Red Aguas Freáticas',
                    'administrator_name'        => null,
                    'center_latitude_degrees'   => null,
                    'center_latitude_minutes'   => null,
                    'center_latitude_seconds'   => null,
                    'center_latitude_direction' => null,
                    'center_longitude_degrees'  => null,
                    'center_longitude_minutes'  => null,
                    'center_longitude_seconds'  => null,
                    'center_longitude_direction'=> null,
                    'rt_active'                 => false,
                    'map_zoom'                  => null,
                    'original_updated'          => false,
                    'filtered_updated'          => false,
                    'created_at'                => Carbon::now(),
                    'updated_at'                => Carbon::now(),
                ]
            ]
        );
    }

    /**
     * down the database seeds.
     *
     * @return void
     */
    public function down()
    {
        DB::connection('administrator')->table('net')->delete();
    }
}
